name = "taoyuan2"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "directory"
dir = ".next"

# Exclude cache files from upload
[[build.upload.rules]]
type = "exclude"
globs = [
  "cache/**",
  "**/cache/**",
  "**/*.pack",
  "**/webpack/**"
]